###
GET http://localhost:8080/v1/services/getStatics

###
GET http://localhost:8080/v1/services/getMethods/
###
GET http://localhost:8080/checkstatus
###
POST http://localhost:8080/v1/users/create
Content-Type: application/json
x-api-key: 4361424c00602739d2637f2ecf4ff7dca64a3b67b0f76d03fca59cbea096e24afa7566f067ac20219fdfd25a4166d67c3d35066a3d2c2656b40d3f5c860c0059

{
    "userName": "TEST1",
    "email": "TEST1@gmail.com",
    "userId": 2
}
### nếu có dấu , sau 2 thì sẽ bị lỗi::: Unexpected token } in JSON at position
### nếu không dùng app.use(express.json()) thì sẽ gặp lỗi::: Cannot read properties of undefined (req.body === undefined)
###
POST http://localhost:8080/v1/users/verifyOtp
Content-Type: application/json

{
    "email": "TEST2@gmail.com",
    "otp": "805906"
}
###vscode-file://vscode-app/c:/Users/vovan/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html
POST http://localhost:8080/v1/users/resgisterUser
Content-Type: application/json

{
    "email": "abcd@gmail.com"
}